from collections import Counter
import string
import random 

messaggio = """
NEL MEZZO DEL CAMMIN DI NOSTRA VITA MI RITROVAI PER UNA SELVA OSCURA CH LA DIRITTA VIA ERA SMARRITA AHI QUANTO A DIR QUAL ERA COSA DURA ESTA SELVA SELVAGGIA E ASPRA E FORTE CHE NEL PENSIER RINOVA LA PAURA TANT AMARA CHE POCO PIU MORTE MA PER TRATTAR DEL BEN CHII VI TROVAI DIRD DE IALTRE COSE CHII VHO SCORTE LO NON SO BEN RIDIR COMII VINTRAI TANTERA PIEN DI SONNO A QUEL PUNTO CHE LA VERACE VIA ABBANDONAI MA POI CHII FUI AL PI DUN COLLE GIUNTO LA DOVE TERMINAVA QUELLA VALLE CHE MAVEA DI PAURA IL COR COMPUNTO GUARDAI IN ALTO E VIDI LE SUE SPALLE VESTITE GIA DE RAGGI DEL PIANETA CHE MENA DRITTO ALTRUI PER OGNE CALLE ALLOR FU LA PAURA UN POCO QUETA CHE NEL LAGO DEL COR MERA DURATA LA NOTTE CHI PASSAI CON TANTA PIETA E COME QUEI CHE CON LENA AFFANNATA USCITO FUOR DEL PELAGO A LA RIVA SI VOLGE A LACQUA PERIGLIOSA E GUATA COSI LANIMO MIO CHANCOR FUGGIVA SI VOLSE A RETRO A RIMIRAR LO PASSO CHE NON LASCIO GIA MAI PERSONA VIVA POI CHI POSATO UN POCO IL CORPO LASSO RIPRESI VIA PER LA PIAGGIA DISERTA SI CHE I PI FERMO SEMPRE ERA IL PIL BASSO ED ECCO QUASI AL COMINCIAR DE IERTA UNA LONZA LEGGERA E PRESTA MOLTO CHE DI PEL MACOLATO ERA COVERTA E NON MI SI PARTIA DINANZI AL VOLTO ANZI MPEDIVA TANTO IL MIO CAMMINO CHII FUI PER RITORNAR PIL VOLTE VOLTO TEMPERA DAL PRINCIPIO DEL MATTINO E L SOL MONTAVA N SU CON QUELLE STELLE CHERAN CON LUI QUANDO IAMOR DIVINO MOSSE DI PRIMA QUELLE COSE BELLE SI CHA BENE SPERAR MERA CAGIONE DI QUELLA FIERA A LA GAETTA PELLE LORA DEL TEMPO E LA DOLCE STAGIONE MA NON SI CHE PAURA NON MI DESSE LA VISTA CHE MAPPARVE DUN LEONE QUESTI PAREA CHE CONTRA ME VENISSE CON LA TESTALTA E CON RABBIOSA FAME SI CHE PAREA CHE LAERE NE TREMESSE ED UNA LUPA CHE DI TUTTE BRAME SEMBIAVA CARCA NE LA SUA MAGREZZA E MOLTE GENTI F GIA VIVER GRAME QUESTA MI PORSE TANTO DI GRAVEZZA CON LA PAURA CHUSCIA DI SUA VISTA CHIO PERDEI LA SPERANZA DE IALTEZZA E QUAL QUEI CHE VOLONTIERI ACQUISTA E GIUGNE L TEMPO CHE PERDER LO FACE CHE N TUTTI SUOI PENSIER PIANGE E SATTRISTA TAL MI FECE LA BESTIA SANZA PACE CHE VENENDOMI NCONTRO A POCO A POCO MI RIPIGNEVA LA DOVE I SOL TACE MENTRE CHI ROVINAVA IN BASSO LOCO DINANZI A LI OCCHI MI SI FU OFFERTO CHI PER LUNGO SILENZIO PAREA FIOCO QUANDO VIDI COSTUI NEL GRAN DISERTO MISERERE DIME GRIDAI A LUI QUAL CHE TU SII OD OMBRA OD OMO CERTO RISPUOSEMI NON OMO OMO GIA FUI E LI PARENTI MIEI FURON LOMBARDI MANTOANI PER PATRIA AMBEDUI NACQUI SUB LULIO ANCOR CHE FOSSE TARDI E VISSI A ROMA SOTTO BUONO AUGUSTO NEL TEMPO DE LI DI FALSI E BUGIARDI POETA FUI E CANTAI DI QUEL GIUSTO FIGLIUOL DANCHISE CHE VENNE DI TROIA POI CHE L SUPERBO ILIN FU COMBUSTO MA TU PERCH RITORNI A TANTA NOIA PERCH NON SALI IL DILETTOSO MONTE CH PRINCIPIO E CAGION DI TUTTA GIOIA OR SE TU QUEL VIRGILIO E QUELLA FONTE CHE SPANDI DI PARLAR SI LARGO FIUME RISPUOSIO LUI CON VERGOGNOSA FRONTE O DELI ALTRI POETI ONORE E LUME VAGLIAMI I LUNGO STUDIO E L GRANDE AMORE CHE MHA FATTO CERCAR LO TUO VOLUME TU SE LO MIO MAESTRO EL MIO AUTORE TU SE SOLO COLUI DA CU IO TOLSI LO BELLO STILO CHE MHA FATTO ONORE VEDI LA BESTIA PER CU IO MI VOLSI AIUTAMI DA LEI FAMOSO SAGGIO CHELLA MI FA TREMAR LE VENE E I POLSI A TE CONVIEN TENERE ALTRO VIAGGIO RISPUOSE POI CHE LAGRIMAR MI VIDE SE VUO CAMPAR DESTO LOCO SELVAGGIO CH QUESTA BESTIA PER LA QUAL TU GRIDE NON LASCIA ALTRUI PASSAR PER LA SUA VIA MA TANTO LO MPEDISCE CHE LUCCIDE E HA NATURA SI MALVAGIA E RIA CHE MAI NON EMPIE LA BRAMOSA VOGLIA E DOPO L PASTO HA PIT FAME CHE PRIA MOLTI SON LI ANIMALI A CUI SAMMOGLIA E PILL SARANNO ANCORA INFIN CHE I VELTRO VERRA CHE LA FARA MORIR CON DOGLIA QUESTI NON CIBERA TERRA N PELTRO MA SAPIENZA AMORE E VIRTUTE E SUA NAZION SARA TRA FELTRO E FELTRO
"""

lettere_ordinate_italiano = ["E", "A", "I", "O", "N", "L", "R", "T", "S", "C", "D", "P", "U", "M", "V", "G", "H", "F", "B", "Q", "Z"]

# originale -> cifrato
tabella_sostituzione = {
    'A': 'Q',    'E': 'T',    'I': 'O',    'O': 'G',    'L': 'S',    'R': 'P',
    'T': 'Z',    'N': 'F',    'S': 'L',    'C': 'E',    'P': 'H',    'M': 'D',
    'U': 'A',    'D': 'R',    'V': 'C',    'G': 'U',    'H': 'I',    'F': 'V',
    'B': 'N',    'Q': 'B',    'Z': 'M'
}

# cifrato -> originale
tabella_sostituzione_inversa = {
    'Q': 'A',    'T': 'E',    'O': 'I',    'G': 'O',  
    'S': 'L',    'P': 'R',    'Z': 'T',    'F': 'N',  
    'L': 'S',    'E': 'C',    'H': 'P',    'D': 'M',  
    'A': 'U',    'R': 'D',    'C': 'V',    'U': 'G',  
    'I': 'H',    'V': 'F',    'N': 'B',    'B': 'Q',  
    'M': 'Z'
}

def cifra(messaggio, tabella_sostituzione):
    messaggio_cifrato = ''

    for lettera in messaggio:
        if lettera in lettere_ordinate_italiano:
            messaggio_cifrato += tabella_sostituzione[lettera]
        else:
            messaggio_cifrato += lettera

    return messaggio_cifrato

messaggio_cifrato = cifra(messaggio, tabella_sostituzione)

with open("messaggio_cifrato.txt", "w") as file:
    file.write(messaggio_cifrato)
